### ISSUE TITLE
Feature: Newtype wrapping & unwrapping

### ISSUE THREAD

**Issue by eric-corumdigital** [garyb/purescript-codec-argonaut#25]
Some version of this would be handy:

```
unwrapCodec ∷ ∀ m a b. Newtype a b ⇒ Applicative m ⇒ BasicCodec m a b
unwrapCodec = basicCodec (pure <<< unwrap) wrap

wrapCodec ∷ ∀ m a b. Newtype a b ⇒ Applicative m ⇒ BasicCodec m b a
wrapCodec = basicCodec (pure <<< wrap) unwrap
```

There is already a transitive dependency on `purescript-newtypes`.

**Comment by garyb** [comment]
The codecs are profunctors, so you can use `unwrapIso` / `wrapIso` from `purescript-profunctor`.

**Comment by garyb** [comment]
I guess I should mention this in the readme, given it's been asked before too: #23

**Comment by eric-corumdigital** [comment]
Wasn't aware of those definitions. Thanks.
