### ISSUE TITLE
Make prismaticCodec decoder return either

### ISSUE THREAD

**Issue by yaitskov** [garyb/purescript-codec-argonaut#57]
Type of decoder function used in prismaticCodec  return Maybe, so reporting details about syntax error is not possible.

**Comment by garyb** [comment]
You may as well create a codec without the "prismatic" helper at that point, `Codec.codec'` is `(Json -> Either JsonDecodeError a) -> (a -> Json) -> JsonCodec a` when used for a `JsonCodec`.
